name: run test.py

on: 
  
  schedule:
    - cron: '*/15 7-18 * * *'  # Every 30 seconds from 7 am to 6 pm
    - cron: '0 0-6,19-23 * * *'  # Every hour from 12 am to 6 am and 7 pm to 11 pm
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install beautifulsoup4

      - name: execute py script # run main.py
        run: python main.py

      # - name: Set up Git
      #   run: |
      #     git config --global user.email "dayzmerollingggg@users.noreply.github.com"
      #     git config --global user.name "Daisy Gan"
      #     git fetch
      #     git checkout main

      - name: add and commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push origin main
        env:
          TOKEN: ${{ secrets.UTD_WEB_SCRAPE_KEY }}